### ISSUE TITLE
Ridge histograms

### ISSUE THREAD

**Issue by LucaMingarelli** [tpvasconcelos/ridgeplot#194]
It would be useful to add the option to histograms instead of KDEs.

**Comment by tpvasconcelos** [comment]
Hey @LucaMingarelli, apologies for the delay.

I would love to see this feature in ridgeplot! I think some work needs to be done in designing a good and consistent API, figuring out reasonable default values (e.g., `marker_line_color`, `marker_line_width`, `barmode`, `bargap`, `bargroupgap`, etc...) and in making sure we don't introduce any breaking changes to the current functionality.

I'll open a draft PR with some preliminary work to get this going. Let me know if you are interested in helping out.

Here's an example taken from , where I tried to convert this _area_ plot:

<img width="500" src="https://github.com/user-attachments/assets/f05f6008-34c4-4583-b21c-b88544f5466b">

into a _bar_ / _histogram_ plot:

<img width="500" src="https://github.com/user-attachments/assets/a2085d58-24a4-4965-ae34-cfb55f6b2234">

**Comment by tpvasconcelos** [comment]
Draft PR: #208

Feel free to take a look and help out

**Comment by tpvasconcelos** [comment]
Quick status update: currently implementing the new `fillgradient` colormode for histograms. This is taking longer than expected  due to recent changes that were merged before I was able to finish this implementation.

Here's a simple example:

![image](https://github.com/user-attachments/assets/4d32536a-6c91-48c8-85ae-01028be22f24)

But this still needs some work as (for instance) the z-order is not working properly when mixing area/density plots with bar/histogram plots

![image](https://github.com/user-attachments/assets/375b27a1-1a61-43a4-b65b-bcb2c45276dc)

**Comment by tpvasconcelos** [comment]
Another update: z-order issue fixed! ✅ 

![image](https://github.com/user-attachments/assets/48013dcd-db7f-4ddc-a534-2fb89aea869b)

**Comment by tpvasconcelos** [comment]
See live example at: https://ridgeplot.readthedocs.io/en/0.3.0/getting_started/getting_started.html#basic-example

🚀🚀🚀
