### ISSUE TITLE
Importing ridgeplot fails with scipy 1.14.1 with "symbol not found in flat namespace '_npy_cabs'"

### ISSUE THREAD

**Issue by cduvallet** [tpvasconcelos/ridgeplot#197]
This is more of an FYI for visibility than an issue that needs action, but importing ridgeplot fails when using scipy 1.14.1 ("symbol not found in flat namespace '_npy_cabs'")

Issue has been raised with scipy maintainers: https://github.com/scipy/scipy/issues/21434

I'm on Mac OS 14.6.1, Python 3.10.14. Downgrading scipy solved the issue:

```
pip install --upgrade scipy==1.14.0
```

**Comment by nickodell** [comment]
This issue is fixed in statsmodels==0.14.3, see https://github.com/statsmodels/statsmodels/issues/9333

**Comment by tpvasconcelos** [comment]
Thanks @cduvallet for reporting the issue and @nickodell for referencing the relevant issue on statsmodels.

Since the problem seems to be which `statsmodels==0.14.2`, I have removed it as a valid dependency in #198 :

![image](https://github.com/user-attachments/assets/8bedfb8f-37f8-454d-a627-cff447e5c8c9)

**Comment by tpvasconcelos** [comment]
A new released has been published to PyPi: https://pypi.org/project/ridgeplot/0.1.26/

For anyone landing here looking for a solution, just upgrade to the latest version of ridgeplot:

```
pip install -U ridgeplot
```

or lock to the latest version:

```
pip install ridgeplot==0.1.26
```

**Comment by wch** [comment]
I filed an issue on pyodide to update statsmodels from 0.14.2 to 0.14.3: https://github.com/pyodide/pyodide/issues/5093

However, I think this will be a nontrivial task because that version of statsmodels wants an updated version of numpy and scipy.

**Comment by tpvasconcelos** [comment]
@wch let me know if there is anything I can do from my end :)  

Python's dependency specification doesn't allow for complex exclusion rules such as `statsmodels>=0.12 & !(scipy==1.14.1 & statsmodels==0.14.2 & numpy==2.1.0)` so I opted for the stricter `statsmodels>=0.12,!=0.14.2` approach.

Apologies if this interfered with your workflow! Better to get the error here rather than an obscure exception at runtime I guess...
